import type { SalesData } from "./types"
import Papa from "papaparse"

// Sample data to use as fallback if fetching fails
const SAMPLE_SALES_DATA: SalesData[] = [
  {
    "Sales Document No.": 500055,
    "Sales Order Date": "2025-02-12",
    "Customer Name": "Adani Power",
    "Customer Code": "CUST008",
    "Customer Category": "Enterprise",
    "Sales Organization": "North India",
    "Billing Document": 700055,
    "Billing Date": "2025-02-16",
    "Invoice Due Date": "2025-04-17",
    "Product Code": "PRD1006",
    "Product Name": "Cement Bags",
    "Quantity Sold": 1293,
    "Unit Price (₹)": 500,
    "Total Revenue (₹ Lakh)": 6.46,
    "Cost Price per Unit (₹)": 350,
    "Total Cost (₹ Lakh)": 4.53,
    "Profit (₹ Lakh)": 1.94,
    "Gross Margin %": 30.0,
    "Discount (%)": 4,
    "Final Invoice Value (₹ Lakh)": 6.21,
    "Payment Status": "Unpaid",
    "Payment Terms": "Net 45 Days",
    "Order Priority": "Medium",
    "Sales Rep Name": "Vikram Patel",
    Region: "Gurgaon",
    "Delivery Status": "Shipped",
  },
  {
    "Sales Document No.": 500056,
    "Sales Order Date": "2025-02-15",
    "Customer Name": "Reliance Industries",
    "Customer Code": "CUST002",
    "Customer Category": "Enterprise",
    "Sales Organization": "West India",
    "Billing Document": 700056,
    "Billing Date": "2025-02-20",
    "Invoice Due Date": "2025-04-20",
    "Product Code": "PRD1002",
    "Product Name": "Steel Pipes",
    "Quantity Sold": 850,
    "Unit Price (₹)": 1200,
    "Total Revenue (₹ Lakh)": 10.2,
    "Cost Price per Unit (₹)": 800,
    "Total Cost (₹ Lakh)": 6.8,
    "Profit (₹ Lakh)": 3.4,
    "Gross Margin %": 33.3,
    "Discount (%)": 2,
    "Final Invoice Value (₹ Lakh)": 10.0,
    "Payment Status": "Paid",
    "Payment Terms": "Net 30 Days",
    "Order Priority": "High",
    "Sales Rep Name": "Priya Sharma",
    Region: "Mumbai",
    "Delivery Status": "Delivered",
  },
  {
    "Sales Document No.": 500057,
    "Sales Order Date": "2025-02-18",
    "Customer Name": "Tata Motors",
    "Customer Code": "CUST005",
    "Customer Category": "Enterprise",
    "Sales Organization": "East India",
    "Billing Document": 700057,
    "Billing Date": "2025-02-22",
    "Invoice Due Date": "2025-03-22",
    "Product Code": "PRD1004",
    "Product Name": "Aluminum Sheets",
    "Quantity Sold": 500,
    "Unit Price (₹)": 900,
    "Total Revenue (₹ Lakh)": 4.5,
    "Cost Price per Unit (₹)": 650,
    "Total Cost (₹ Lakh)": 3.25,
    "Profit (₹ Lakh)": 1.25,
    "Gross Margin %": 27.8,
    "Discount (%)": 3,
    "Final Invoice Value (₹ Lakh)": 4.37,
    "Payment Status": "Unpaid",
    "Payment Terms": "Net 30 Days",
    "Order Priority": "Medium",
    "Sales Rep Name": "Rahul Gupta",
    Region: "Kolkata",
    "Delivery Status": "Processing",
  },
  {
    "Sales Document No.": 500058,
    "Sales Order Date": "2025-02-20",
    "Customer Name": "Infosys",
    "Customer Code": "CUST010",
    "Customer Category": "Corporate",
    "Sales Organization": "South India",
    "Billing Document": 700058,
    "Billing Date": "2025-02-25",
    "Invoice Due Date": "2025-03-25",
    "Product Code": "PRD1008",
    "Product Name": "Office Furniture",
    "Quantity Sold": 50,
    "Unit Price (₹)": 15000,
    "Total Revenue (₹ Lakh)": 7.5,
    "Cost Price per Unit (₹)": 10000,
    "Total Cost (₹ Lakh)": 5.0,
    "Profit (₹ Lakh)": 2.5,
    "Gross Margin %": 33.3,
    "Discount (%)": 5,
    "Final Invoice Value (₹ Lakh)": 7.13,
    "Payment Status": "Paid",
    "Payment Terms": "Net 15 Days",
    "Order Priority": "High",
    "Sales Rep Name": "Ananya Desai",
    Region: "Bangalore",
    "Delivery Status": "Delivered",
  },
  {
    "Sales Document No.": 500059,
    "Sales Order Date": "2025-01-10",
    "Customer Name": "Bharti Airtel",
    "Customer Code": "CUST007",
    "Customer Category": "Enterprise",
    "Sales Organization": "North India",
    "Billing Document": 700059,
    "Billing Date": "2025-01-15",
    "Invoice Due Date": "2025-02-15",
    "Product Code": "PRD1003",
    "Product Name": "Network Equipment",
    "Quantity Sold": 25,
    "Unit Price (₹)": 50000,
    "Total Revenue (₹ Lakh)": 12.5,
    "Cost Price per Unit (₹)": 35000,
    "Total Cost (₹ Lakh)": 8.75,
    "Profit (₹ Lakh)": 3.75,
    "Gross Margin %": 30.0,
    "Discount (%)": 2,
    "Final Invoice Value (₹ Lakh)": 12.25,
    "Payment Status": "Paid",
    "Payment Terms": "Net 30 Days",
    "Order Priority": "Critical",
    "Sales Rep Name": "Vikram Patel",
    Region: "Delhi",
    "Delivery Status": "Delivered",
  },
  {
    "Sales Document No.": 500060,
    "Sales Order Date": "2025-01-15",
    "Customer Name": "Mahindra & Mahindra",
    "Customer Code": "CUST004",
    "Customer Category": "Enterprise",
    "Sales Organization": "West India",
    "Billing Document": 700060,
    "Billing Date": "2025-01-20",
    "Invoice Due Date": "2025-03-20",
    "Product Code": "PRD1005",
    "Product Name": "Automotive Parts",
    "Quantity Sold": 1000,
    "Unit Price (₹)": 800,
    "Total Revenue (₹ Lakh)": 8.0,
    "Cost Price per Unit (₹)": 550,
    "Total Cost (₹ Lakh)": 5.5,
    "Profit (₹ Lakh)": 2.5,
    "Gross Margin %": 31.3,
    "Discount (%)": 3,
    "Final Invoice Value (₹ Lakh)": 7.76,
    "Payment Status": "Unpaid",
    "Payment Terms": "Net 60 Days",
    "Order Priority": "Medium",
    "Sales Rep Name": "Priya Sharma",
    Region: "Pune",
    "Delivery Status": "Shipped",
  },
  {
    "Sales Document No.": 500061,
    "Sales Order Date": "2025-01-18",
    "Customer Name": "Wipro",
    "Customer Code": "CUST011",
    "Customer Category": "Corporate",
    "Sales Organization": "South India",
    "Billing Document": 700061,
    "Billing Date": "2025-01-22",
    "Invoice Due Date": "2025-02-22",
    "Product Code": "PRD1009",
    "Product Name": "IT Hardware",
    "Quantity Sold": 100,
    "Unit Price (₹)": 12000,
    "Total Revenue (₹ Lakh)": 12.0,
    "Cost Price per Unit (₹)": 8500,
    "Total Cost (₹ Lakh)": 8.5,
    "Profit (₹ Lakh)": 3.5,
    "Gross Margin %": 29.2,
    "Discount (%)": 4,
    "Final Invoice Value (₹ Lakh)": 11.52,
    "Payment Status": "Paid",
    "Payment Terms": "Net 30 Days",
    "Order Priority": "High",
    "Sales Rep Name": "Ananya Desai",
    Region: "Chennai",
    "Delivery Status": "Delivered",
  },
  {
    "Sales Document No.": 500062,
    "Sales Order Date": "2025-01-20",
    "Customer Name": "ONGC",
    "Customer Code": "CUST003",
    "Customer Category": "Enterprise",
    "Sales Organization": "North India",
    "Billing Document": 700062,
    "Billing Date": "2025-01-25",
    "Invoice Due Date": "2025-03-25",
    "Product Code": "PRD1007",
    "Product Name": "Industrial Pipes",
    "Quantity Sold": 300,
    "Unit Price (₹)": 3000,
    "Total Revenue (₹ Lakh)": 9.0,
    "Cost Price per Unit (₹)": 2100,
    "Total Cost (₹ Lakh)": 6.3,
    "Profit (₹ Lakh)": 2.7,
    "Gross Margin %": 30.0,
    "Discount (%)": 2,
    "Final Invoice Value (₹ Lakh)": 8.82,
    "Payment Status": "Unpaid",
    "Payment Terms": "Net 45 Days",
    "Order Priority": "High",
    "Sales Rep Name": "Rahul Gupta",
    Region: "Dehradun",
    "Delivery Status": "Processing",
  },
  {
    "Sales Document No.": 500063,
    "Sales Order Date": "2025-01-25",
    "Customer Name": "Larsen & Toubro",
    "Customer Code": "CUST006",
    "Customer Category": "Enterprise",
    "Sales Organization": "West India",
    "Billing Document": 700063,
    "Billing Date": "2025-01-30",
    "Invoice Due Date": "2025-03-01",
    "Product Code": "PRD1001",
    "Product Name": "Construction Materials",
    "Quantity Sold": 2000,
    "Unit Price (₹)": 400,
    "Total Revenue (₹ Lakh)": 8.0,
    "Cost Price per Unit (₹)": 280,
    "Total Cost (₹ Lakh)": 5.6,
    "Profit (₹ Lakh)": 2.4,
    "Gross Margin %": 30.0,
    "Discount (%)": 3,
    "Final Invoice Value (₹ Lakh)": 7.76,
    "Payment Status": "Paid",
    "Payment Terms": "Net 30 Days",
    "Order Priority": "Medium",
    "Sales Rep Name": "Vikram Patel",
    Region: "Mumbai",
    "Delivery Status": "Delivered",
  },
  {
    "Sales Document No.": 500064,
    "Sales Order Date": "2025-01-28",
    "Customer Name": "TCS",
    "Customer Code": "CUST009",
    "Customer Category": "Corporate",
    "Sales Organization": "East India",
    "Billing Document": 700064,
    "Billing Date": "2025-02-02",
    "Invoice Due Date": "2025-03-02",
    "Product Code": "PRD1010",
    "Product Name": "Office Supplies",
    "Quantity Sold": 500,
    "Unit Price (₹)": 1000,
    "Total Revenue (₹ Lakh)": 5.0,
    "Cost Price per Unit (₹)": 650,
    "Total Cost (₹ Lakh)": 3.25,
    "Profit (₹ Lakh)": 1.75,
    "Gross Margin %": 35.0,
    "Discount (%)": 5,
    "Final Invoice Value (₹ Lakh)": 4.75,
    "Payment Status": "Unpaid",
    "Payment Terms": "Net 30 Days",
    "Order Priority": "Low",
    "Sales Rep Name": "Rahul Gupta",
    Region: "Kolkata",
    "Delivery Status": "Pending",
  },
]

export async function fetchSalesData(): Promise<SalesData[]> {
  try {
    const response = await fetch(
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/sales_register-jlHlJ5bFJDWrVcWeyQjCdkk4JtNXvE.csv",
    )

    if (!response.ok) {
      console.warn(`Failed to fetch CSV: ${response.status}. Using sample data instead.`)
      return SAMPLE_SALES_DATA
    }

    const csvText = await response.text()

    return new Promise((resolve, reject) => {
      Papa.parse(csvText, {
        header: true,
        dynamicTyping: true,
        complete: (results) => {
          if (results.data && results.data.length > 0) {
            const data = results.data as SalesData[]
            // Filter out any empty rows
            const filteredData = data.filter((row) => row["Sales Document No."] && row["Customer Name"])

            if (filteredData.length > 0) {
              resolve(filteredData)
            } else {
              console.warn("CSV parsed but no valid data found. Using sample data instead.")
              resolve(SAMPLE_SALES_DATA)
            }
          } else {
            console.warn("CSV parsed but no data found. Using sample data instead.")
            resolve(SAMPLE_SALES_DATA)
          }
        },
        error: (error) => {
          console.error("Error parsing CSV:", error)
          console.warn("Using sample data instead.")
          resolve(SAMPLE_SALES_DATA)
        },
      })
    })
  } catch (error) {
    console.error("Error fetching sales data:", error)
    console.warn("Using sample data instead.")
    return SAMPLE_SALES_DATA
  }
}

