import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import dynamic from "next/dynamic"
import type { SalesData } from "@/lib/types"
import { motion } from "framer-motion"

const LazyTopCustomersChart = dynamic(() => import("@/components/charts/top-customers-chart").then(mod => ({ default: mod.TopCustomersChart })), { ssr: false })
const LazyProductPerformanceChart = dynamic(() => import("@/components/charts/product-performance-chart").then(mod => ({ default: mod.ProductPerformanceChart })), { ssr: false })
const LazySalesRepPerformanceChart = dynamic(() => import("@/components/charts/sales-rep-performance-chart").then(mod => ({ default: mod.SalesRepPerformanceChart })), { ssr: false })
const LazyPendingInvoicesChart = dynamic(() => import("@/components/charts/pending-invoices-chart").then(mod => ({ default: mod.PendingInvoicesChart })), { ssr: false })
const LazyOrderPipelineChart = dynamic(() => import("@/components/charts/order-pipeline-chart").then(mod => ({ default: mod.OrderPipelineChart })), { ssr: false })
const LazyCustomerRetentionTable = dynamic(() => import("@/components/charts/customer-retention-table").then(mod => ({ default: mod.CustomerRetentionTable })), { ssr: false })

interface SecondaryChartsProps {
  data: SalesData[]
}

export function SecondaryCharts({ data }: SecondaryChartsProps) {
  return (
    <>
      <motion.div className="grid grid-cols-1 md:grid-cols-2 gap-6" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
        <Card>
          <CardHeader>
            <CardTitle>Top Customers</CardTitle>
            <CardDescription>Highest revenue generating customers</CardDescription>
          </CardHeader>
          <CardContent>
            <LazyTopCustomersChart data={data} />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Product Performance</CardTitle>
            <CardDescription>Sales distribution by product</CardDescription>
          </CardHeader>
          <CardContent>
            <LazyProductPerformanceChart data={data} />
          </CardContent>
        </Card>
      </motion.div>

      <motion.div className="grid grid-cols-1 md:grid-cols-2 gap-6" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
        <Card>
          <CardHeader>
            <CardTitle>Pending Invoices</CardTitle>
            <CardDescription>Aging analysis of outstanding payments</CardDescription>
          </CardHeader>
          <CardContent>
            <LazyPendingInvoicesChart data={data} />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Sales Rep Performance</CardTitle>
            <CardDescription>Revenue generated by sales representatives</CardDescription>
          </CardHeader>
          <CardContent>
            <LazySalesRepPerformanceChart data={data} />
          </CardContent>
        </Card>
      </motion.div>

      <motion.div className="grid grid-cols-1 md:grid-cols-2 gap-6" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
        <Card>
          <CardHeader>
            <CardTitle>Order Pipeline</CardTitle>
            <CardDescription>Orders at different stages</CardDescription>
          </CardHeader>
          <CardContent>
            <LazyOrderPipelineChart data={data} />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Customer Retention</CardTitle>
            <CardDescription>Repeat purchase analysis</CardDescription>
          </CardHeader>
          <CardContent>
            <LazyCustomerRetentionTable data={data} />
          </CardContent>
        </Card>
      </motion.div>
    </>
  )
} 